services:
  php:
    container_name: ${PROJECT_NAME}-php
    build:
      context: .
      dockerfile: ./.deployment/docker/containers/php/Dockerfile
    depends_on:
      - database
    networks:
      service:
        aliases:
          - pod
    env_file:
      - .env
    environment:
      - ENV=/home/www-data/.ashrc
    volumes:
      - ./:/srv/app:rw
      - ./.deployment/docker/containers/php/www.conf:/etc/php8.1.3/php-fpm.conf
      - ./.deployment/docker/containers/php/php.ini:/usr/local/etc/php/php.ini
      - ./.deployment/docker/aliases/.ashrc:/home/www-data/.ashrc
    command: --define opcache.validate_timestamps=On

  nginx:
    container_name: ${PROJECT_NAME}-nginx
    depends_on:
      - php
    networks:
      - service
    image: nginx:1.20-alpine
    environment:
      - HTTPS_METHOD=noredirect
    volumes:
      - ./public:/srv/app/public:ro
      - ./.deployment/docker/containers/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9000:8080"

  database:
    container_name: ${PROJECT_NAME}-db
    image: mariadb:10.4.19
    env_file:
      - .env
    networks:
      - service
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "9001:3306"

  rabbitmq:
    restart: unless-stopped
    container_name: ${PROJECT_NAME}-rabbitmq
    image: rabbitmq:3-management
    networks:
      - service
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    ports:
      - "9002:5672"
      - "9003:15672"

volumes:
  database_data:
  rabbitmq_volume:

networks:
  service:
    name: service
